server:
  stage: DEV
  dbUrl: 52.54.69.220
  port: 5442
  dbUsername: root
  dbPassword: 1234
  dbName: testhaha
  synchronize: true
  sapUrl: http://192.168.20.17:8880/apigoplus/GetBillTo/
  sapApiToken: z@hz3sNY#0ohB9SspeE9@fLDQ%r65x$k8LxL28VH72FfvRWgCn
  baseUrl: this build new env
  project: Build Dev:v0.1.3a on 19/11/22
  release: 0.0.25